name: Trigger Tests

on:
  push:
    branches:
      - main

jobs:
  notify_test_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to test repository
        uses: actions/http-call@v2
        with:
          url: https://api.github.com/repos/<Sneha781>/test/dispatches
          method: POST
          headers: '{"Authorization": "Bearer < secrets,PERSONAL_ACCESS_TOKEN>", "Content-Type": "application/json"}'
          body: '{"event_type": "trigger-tests"}'
